services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: d208
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    secrets:
      - mysql_password

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  springboot-app:
    build: ./user-service
    container_name: springboot-app
    restart: always  # 서버 재시작이나 충돌시 항상 재시작
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./secrets/mysql_password.txt:/run/secrets/mysql_password:ro
      - ./secrets/jwt_secret.txt:/run/secrets/jwt_secret:ro
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network
    secrets:
      - mysql_password
      - jwt_secret
    entrypoint: >
      sh -c "export MYSQL_PASSWORD=$$(cat /run/secrets/mysql_password) &&
            export JWT_SECRET=$$(cat /run/secrets/jwt_secret) &&
            java -jar app.jar"


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always  # 서버 재시작이나 충돌시 항상 재시작
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 추가
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/S12P31D208/S12P31D208/fitmily_backend/nginx/conf.d:/etc/nginx/conf.d  # 절대경로로 변경했음.
      - /etc/letsencrypt/live/k12d208.p.ssafy.io:/etc/nginx/certs:ro
      - /etc/letsencrypt/archive/k12d208.p.ssafy.io:/etc/nginx/archive:ro
      # - /etc/letsencrypt/live/k12d208.p.ssafy.io:/etc/nginx/certs  # 인증서 경로 마운트
      # - /etc/letsencrypt/archive:/etc/nginx/archive  # 필요한 경우
    depends_on:
      - springboot-app
    networks:
      - app-network


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  jenkins:
    # image: jenkins/jenkins:lts-jdk17
    image: custom-jenkins:latest  # 커스텀 이미지 사용
    container_name: jenkins
    user: root
    restart: always  # 서버 재시작이나 충돌시 항상 재시작
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - "JAVA_OPTS=-Dhudson.model.UpdateCenter.pluginDownloadReadTimeoutSeconds=180 -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
      - TZ=Asia/Seoul
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data:
  grafana_data:
  jenkins_home:

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt