services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootrootroot
      MYSQL_DATABASE: mydb
      MYSQL_USER: d208
      MYSQL_PASSWORD: 208208208
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  springboot-app:
    build: ./user-service
    container_name: springboot-app
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_PASSWORD=208208208
      - SPRING_JWT_SECRET=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network
    entrypoint: >
      sh -c "java -jar app.jar"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/S12P31D208/S12P31D208/fitmily_backend/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/k12d208.p.ssafy.io:/etc/nginx/certs:ro
      - /etc/letsencrypt/archive/k12d208.p.ssafy.io:/etc/nginx/archive:ro
    depends_on:
      - springboot-app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  jenkins:
    image: custom-jenkins:latest
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - "JAVA_OPTS=-Dhudson.model.UpdateCenter.pluginDownloadReadTimeoutSeconds=180 -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
      - TZ=Asia/Seoul
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data:
  grafana_data:
  jenkins_home:
